services:
  - type: web
    name: farah-tilmatine
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: farah_website
      - key: ADMIN_PASSWORD
        sync: false
      - key: SESSION_SECRET
        sync: false